### ISSUE TITLE
RDF::Mongo::Repository not queryable by sparql gem

### ISSUE THREAD

**Issue by jsmpereira** [pius/rdf-mongo#2]
Hi,

I'm using rdf-mongo as my rdf-store with Spira on a Rails app.

While trying to use the sparql gem I found I didn't get any results:

```
ruby-1.8.7-p299 > queryable = RDF::Mongo::Repository.new
=> #<RDF::Mongo::Repository:0x1bbded2()> 
ruby-1.8.7-p299 > sse = SPARQL.parse("SELECT * WHERE { ?s ?p ?o }")
=> #<RDF::Query:0x376c480 @variables={}, @patterns=[#<RDF::Query::Pattern:0x1bb68f8(?s ?p ?o .)>], @options={:context=>false}, @solutions=[]> 
ruby-1.8.7-p299 > sse.execute(queryable)
=> []
```

 gkellogg on #swig gave me a huge help and suggested I'd try

```
r = RDF::Repository.new << queryable
```

and then query r, which worked.

Don't know if this is a known issue, but here you are.

Thanks for all the great work.

**Comment by gkellogg** [comment]
I'm afraid pius hasn't been keeping up with development. It shouldn't take too much to get RDF::Mongo to properly respond as RDF::Queryable, which is what's necessary to work with the SPARQL gem. There is a reasonable Rspec behavior defined in RDF::Spec.

I don't have any time right now to take this on myself, but if you're game, fork the project and I'll help you with setup to get it working properly.

**Comment by jsmpereira** [comment]
Thanks for getting back to me.

I've forked the project and I'll be on #swig. I believe we might be on different timezones, but I hope I can
get back to you later.

I've collected some info on the querying behaviour of the gem. Namely I found out why I was getting no results when querying the entire store.

The sparql query is wrongly being translated to:

<code>[conn6] query: quadb.quads{ s: "http://www.semanticweb.org/ontologies/2011/10/Ontology1321532209875.ow...", st: "u", pt: "u", o: "?o", ot: "u", c: "false", ct: "u", p: "?p" }</code>

More info here: http://pastie.org/3143052

Now, mongodb when searching for o: "?o" and p: "?p" does not get any results. 
I'm tempted to just check for that pattern and not allow mongodb to query on those attributes.

But something tells me it might not be that simple.

Thanks

**Comment by gkellogg** [comment]
I've forked the repo, and made significant progress in my 0.3.0 branch. I have a bit more to do, but it will have to wait until tomorrow. It might work for you reasonably well as is. Check out http://github.com/gkellogg/rdf-mongo.

P.S., now passes all specs, but rdf-spec needs some updates. Also one issue that was marked as pending that needs more investigation. I can't really run full SPARQL specs against it without some further modifications, but it should run everything I previously found as a problem area.

There's likely much more performance optimization that can still be done; for instance, bound variables could be compared with their bound values; right now this is done by just returning all such variables and looking for matches at a higher level.

RDF::DO howto needs to be updated and also needs to be checked out; I'll need to look at that next.
